### PR TITLE
Dannym apidowngrade

### PR DESCRIPTION
**Pull request by dannymeloy**
Addition of API downgrade feature from nmoscommon

### CODE REVIEW

**Comment by andrewbonney** [comment]
Is the downgrade map here the same as the Query API one? If so, is there any reason not to define it in common?

**Comment by dannymeloy** [comment]
> Is the downgrade map here the same as the Query API one? If so, is there any reason not to define it in common?

Yes they're identical, but I thought it was best to keep node-specific info in the node repo and query info in the query repo, etc. even if they're unlikely to ever diverge

**Comment by andrewbonney** [comment]
This ought to be updated to depend upon the newer version of nmoscommon, including the patch bump for the copy fix.

**Comment by andrewbonney** [comment]
The switch to removing keys rather than only letting through those which are permitted seems to cause an issue for one or more of our underlying services. The pipeline manager adds its own metadata to these resources which seems to get carried through. It may be that we're best resolving these cases within the affected services directly.

**Review by andrewbonney — APPROVED** [review]

**Pull request merged**
