### PR TITLE
Refactor PTP clock handling to permit adding via service interface

### LINKED ISSUE #17: External implementations have no way to register their own clocks
Applies to other attributes too, but the Node resources are relatively fixed by the Node API

### PR DESCRIPTION
**Pull request by andrewbonney**
Will resolve #17 once corresponding nmos-common change is merged.

### CODE REVIEW

**Review by simonrankine — COMMENTED** [review]
General point, but this method is getting quite long and involved. I wonder if maybe the clock stuff would be better represented is a separate class somewhere? You seem to repeat the code for finding a clock out of the list of clocks quite a lot!

**Comment by alexrawcliffe** [comment]
@simonrankine Yes I nearly made the same comment when I saw these commits too. In the end I decided that the clock code wasn't passed around the Node very much apart from on these lines so it was probably 'good enough'...

**Comment by andrewbonney** [comment]
Did you mean method or class? I can add another method to split out the following lines if needed, but all I'm going to be able to do is make it return a clock and the iteration number in the loop, which seems a slightly odd thing to return.

```
        for loop_count, clk in enumerate(self.node_data['clocks']):
            if clk_name == clk["name"]:
```

**Comment by andrewbonney** [comment]
Is that a little better?

**Review by alexrawcliffe — COMMENTED** [review]
Yes I think that's tidier - dictionary operations reduce the amount of looping/boilerplate needed a lot...

**Comment by alexrawcliffe** [comment]
Happier @simonrankine ?

**Comment by simonrankine** [comment]
Yes that's a bit better, has reduced the depth of some of the methods as well which is good.

**Review by simonrankine — APPROVED** [review]

**Pull request merged**
